presentation_as_text_stylesheet: 'lib/presentation_as_text.xsl'
presentation_as_html_stylesheet: 'lib/presentation_as_html.xsl'
presentation_as_minimal_html_stylesheet: 'lib/presentation_as_minimal_html.xsl'
presentation_as_editable_html_stylesheet: 'lib/presentation_as_editable_html.xsl'
presentation_from_editable_html_stylesheet: 'lib/presentation_from_editable_html.xsl'
presentation_from_editable_xml_stylesheet: 'lib/presentation_from_editable_xml.xsl'
presentation_as_reference_stylesheet: 'lib/presentation_as_reference.xsl'
presentation_as_tokens_stylesheet: 'lib/presentation_as_tokens.xsl'
