:languages:
  :got:
    :instance_frequencies:
      true
    :source_tag_pattern_filtering:
      true
    :include_new_source_tags:
      "^V":
      "^N":
      "^A":
      "^P":
      "^Mo":
      "^D-":
        "-n"
      "^Df":
      "^C":
    :manual_rules:
      got-rules.db
    :generated_rules:
      got-generated.db
  :cu:
    :manual_rules:
      cu-rules.db
    :fst:
      :normalisation:
        cu-normalisation.ca
      :analysis:
        cu.ca
      :orthography:
        cu-orthographics.ca
    :instance_frequencies:
      true
    :source_tag_pattern_filtering:
      true
  :grc:
    :manual_rules:
      grc-rules.db
    :instance_frequencies:
      true
    :source_tag_pattern_filtering:
      true
    :include_new_source_tags:
      "^N-":
        "-b"
      "^N[^-]":
        "-"
      "^A........-":
        "---------p"
      "^A........[^-]":
        "-"
      "^V":
        "-"
  :la:    
    :manual_rules:
      la-rules.db
    :generated_rules:
      la-generated.db
    :instance_frequencies:
      true
