:languages:
  :fro:
    :instance_frequencies:
      :completion_level:
        any
  :spa:
    :instance_frequencies:
      :completion_level:
        any
  :por:
    :instance_frequencies:
      :completion_level:
        any
  :ang:
    :instance_frequencies:
      :completion_level:
        reviewed_only
  :non:
    :instance_frequencies:
      :completion_level:
        reviewed_only
    :inflections_table:
      true
    :source_tag_pattern_filtering:
      true
  :xcl:
    :instance_frequencies:
      :completion_level:
        reviewed_only
    :inflections_table:
      true
    :source_tag_pattern_filtering:
      true
  :got:
    :instance_frequencies:
      :completion_level:
        reviewed_only
    :source_tag_pattern_filtering:
      true
    :include_new_source_tags:
      "^V":
      "^N":
      "^A":
      "^P":
      "^Mo":
      "^D-":
        "-n"
      "^Df":
      "^C":
    :inflections_table:
      true
  :chu:
    :instance_frequencies:
      :completion_level:
        reviewed_only
    :inflections_table:
      true
    :source_tag_pattern_filtering:
      true
  :grc:
    :instance_frequencies:
      :completion_level:
        reviewed_only
    :source_tag_pattern_filtering:
      true
    :include_new_source_tags:
      "^N-":
        "-b"
      "^N[^-]":
        "-"
      "^A........-":
        "---------p"
      "^A........[^-]":
        "-"
      "^V":
        "-"
    :inflections_table:
      true
  :lat:
    :instance_frequencies:
      :completion_level:
        reviewed_only
    :inflections_table:
      true
    :fst:
      :analysis:
        lat.a
